### ISSUE TITLE
Automatic reconnect

### ISSUE THREAD

**Issue by maximilianloy** [randdusing/BluetoothLE#214]
Hello,

I need to have the phone automatically reconnect to the device after a disconnect and when it is within reach again. At least the "connectGatt" method on Android comes with a autoConnect parameter, but this is hardcoded to "false" in the plugin.

I am wondering if there is a reason for not supporting this parameter in Javascript? To me it looks like exactly the behaviour I need. Does iOS support that behaviour too?

**Comment by randdusing** [comment]
You could call the reconnect function when a disconnected event is receive.

**Comment by maximilianloy** [comment]
If it disconnected because the phone and device got too far away, will the reconnect function make sure to connect as soon as they are within reach again?

**Comment by randdusing** [comment]
I haven't verified the specific behavior, but it should. Calling the plugins reconnect method calls this internally on Android: http://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#connect() while iOS just uses the standard connect method. Neither of them timeout and should automatically connect when the device is within range again. Based on what I've seen with Android so far, I prefer to completely disconnect and close the connection, wait a small timeout and then call connect again rather than reconnect.

**Comment by maximilianloy** [comment]
Sounds great, thanks!
If you completely disconnect and close the connection, does it require to re-discover the services and characteristics? What is the "cost" of closing the connection instead of just re-connecting?

**Comment by randdusing** [comment]
iOS must be discovered on reconnect according to what I added to the README a while back, but I haven't reverified this lately. I can't say exactly what the cost of closing the connection is. The Android Bluetooth stack can be pretty buggy, so I prefer to completely close out the connection. I would test it out and see what works best for you. Just keep in mind that Bluetooth "reliability" seems to vary between Android devices, which is partially why you'll see so many issues. :)
